### ISSUE TITLE
Add mention of alpine

### ISSUE THREAD

**Issue by polarathene** [dockette/adminer#12]
Not sure how I came across this repo as I was querying my search with `docker adminer alpine`, turns out this is alpine based but there doesn't seem to be any mention of that in repo description or README.md?

Perhaps there isn't much reason or value to mention it these days? The repo does convey it's a tiny image for adminer along with table showing various sizes for variants.

**Comment by f3l1x** [comment]
Hi, thanks. Let me clear that, you suggest to mention that this image sis based on alpine? Am I Right?

**Comment by polarathene** [comment]
Yeah it'd be nice for discoverability when looking for alpine images. I tend to use the keyword `alpine` when doing such as it's well known as a docker base image for small containers.

**Comment by f3l1x** [comment]
Resolved b04ab21d38ef911fedbf0daba289dca561cb0a58
