### ISSUE TITLE
Use latest version by default

### ISSUE THREAD

**Issue by enumag** [dockette/adminer#13]
Instead of changing the default value of ENV every time a new version comes out, could we use the latest by default?

Something like this? (Yes it works on alpine.)

```
wget -qO- "https://api.github.com/repos/vrana/adminer/releases/latest" | sed -n 's/\s*"tag_name": "v\?\([0-9.]*\)",/\1/p'
```

**Comment by f3l1x** [comment]
Well, it's not very secure. What about some common file for this repo that can interact with all images?

**Comment by jrdnlc** [comment]
When is this getting updated? I'm still on 4.5.0 and it says 4.6.3 is available. I'm running it in docker

**Comment by f3l1x** [comment]
I've just upgraded Dockerfiles. ;-)

**Comment by f3l1x** [comment]
Closing due to neactivity. Bumped to v4.7.1.
