### ISSUE TITLE
Comparison to official adminer image?

### ISSUE THREAD

**Issue by CZechBoY** [dockette/adminer#15]
Hi,
how is this image different from the [official one](https://hub.docker.com/_/adminer/)? [GitHub](https://github.com/TimWolla/docker-adminer)

**Comment by f3l1x** [comment]
Hi!

- different images for different dbs (postgres, mysql, oracle, mongo)
- https://github.com/dg/adminer-custom image

**Comment by CZechBoY** [comment]
@f3l1x Can we close this or leave it open, so others can find this?
