### ISSUE TITLE
adminer-editor image not available on DockerHub

### ISSUE THREAD

**Issue by W1M0R** [dockette/adminer#28]
Thanks for hosting adminer on DockerHub. Will you be able to do the same for adminer-editor?

**Comment by f3l1x** [comment]
It should be now. Thanks.

https://hub.docker.com/repository/docker/dockette/adminer/tags?page=1&name=editor

![image](https://user-images.githubusercontent.com/538058/88485786-e9936e80-cf78-11ea-9970-05ba206451fa.png)
