### ISSUE TITLE
adminer-editor image uses an outdated version of the app

### ISSUE THREAD

**Issue by W1M0R** [dockette/adminer#29]
The adminer-editor Dockerfile indicates that ADMINER_EDITOR_VERSION=4.7.0 is being used. A newer version is available.

You should be able to use a similar command when updating the ADMINER_VERSION:

`find . -type f -name Dockerfile -exec sed -i '' 's/ENV ADMINER_EDITOR_VERSION=.*/ENV ADMINER_EDITOR_VERSION=4.7.X/g' {} +`

Alternatively, you could add the following lines to your Dockerfile to make it possible for consumers to set the version via docker build args:

```dockerfile
ARG ADMINER_EDITOR_VERSION=4.7.5
ENV ADMINER_EDITOR_VERSION=${ADMINER_EDITOR_VERSION}
```

**Comment by f3l1x** [comment]
I've added your bash oneliner to the readme, thanks.

**Comment by f3l1x** [comment]
Also update to latest version https://github.com/dockette/adminer/commit/742dd579bef22cd6d6f0df79d525e42cf10c88ac#diff-41419fbc789f9bf01eec132b50c80da2
