### ISSUE TITLE
DG image says "File not found" when doing a custom sql query

### ISSUE THREAD

**Issue by aqos156** [dockette/adminer#41]
When I try to execute a custom SQL query in the adminer:dg image, an error appears that says "File not found"

<img width="533" alt="Snímek obrazovky 2021-09-07 v 7 57 02" src="https://user-images.githubusercontent.com/11147374/132291689-3051f4f0-ef2e-450e-8c6c-101262cea205.png">

I'm running the latest version of the image.

**Comment by f3l1x** [comment]
Do you thing it might be related to latest commit since last tagged version? 

https://github.com/dg/adminer-custom/commit/4564b4e0a71d0d9d47568ddb97ae35407400fafd

**Comment by enumag** [comment]
I don't think so. That fix is in autocomplete.php, this error happens when submitting the query. Autocompletion works fine.

**Comment by enumag** [comment]
Okay I looked into it and that latest commit actually fixes this. There was some issue with the textarea and the data were not properly sent. Adminer then kinda misinterpreted the problem and showed an unrelated error message.
