### ISSUE TITLE
Wrong path for tini in debian 

### ISSUE THREAD

**Issue by jensrohloff** [dockette/adminer#44]
https://github.com/dockette/adminer/blob/acfd4f290c6e6a0b99bc53688ed7887271b3102a/adminer-oracle-12/Dockerfile#L53

should be /usr/bin/tini

see
https://github.com/krallin/tini#debian

**Comment by f3l1x** [comment]
Well, I don't know how, but it works. If I change it to `/usr/bin/tini` it doesn't.
