### ISSUE TITLE
Missing php83 binary after recent update

### ISSUE THREAD

**Issue by bganicky** [dockette/adminer#55]
Hi,

after the recent update I get `[FATAL tini (7)] exec /usr/bin/php failed: No such file or directory`. It seems that `php83` must be installed explicitly in `apk add`. It seems that php83 extensions don't actually install the `php83` dependency automatically.

After adding `php83@community` and removing the symbolic link creation, it works as expected.

Thanks!

**Comment by f3l1x** [comment]
Thank you, done

**Comment by bganicky** [comment]
Thanks for a quick response!
