### ISSUE TITLE
MongoDB Support

### ISSUE THREAD

**Issue by kadukeitor** [dockette/adminer#6]
<img width="1063" alt="screen shot 2017-05-23 at 11 47 23 am" src="https://cloud.githubusercontent.com/assets/2692670/26362976/9c6340d0-3fad-11e7-84e3-676dae5aa4c1.png">

**Comment by f3l1x** [comment]
Hi. Thanks for reporting. Which version do you use?

**Comment by kadukeitor** [comment]
I'm using `dockette/adminer:full` thanks for the quick reply !

**Comment by f3l1x** [comment]
@kadukeitor Hmm, I see where is the problem. PHP7 has `mongodb` extension and adminer use `mongo`. 

Could you please try `dockette/adminer:full-php5`? Thank you.

**Comment by kadukeitor** [comment]
Work perfect on `dockette/adminer:full-php5` thanks !!

**Comment by f3l1x** [comment]
No problemo. :tada:
