### ISSUE TITLE
Container takes a long time to stop

### ISSUE THREAD

**Issue by enumag** [dockette/adminer#8]
I'm using the `dockette/adminer:dg` image in the docker-compose.yml I have for development. It works fine, but when I stop the containers (2 postgres databases + adminer), adminer takes much longer to stop than the others (by several seconds). Any idea why this is the case? I would expect adminer to be a relatively light container compared to postgres.

**Comment by f3l1x** [comment]
Any progress here? Have you found out?

**Comment by enumag** [comment]
Unfortunately no.

**Comment by f3l1x** [comment]
Feel free to open it again.

**Comment by enumag** [comment]
Well it's not resolved...

**Comment by f3l1x** [comment]
I understand that, but no more info is provided from you / or me. I'm closing it due to inactivity.

**Comment by enumag** [comment]
I'd like to provide more info but I have no idea how to find out anything about this. Any tips?

**Comment by f3l1x** [comment]
Well, I've done some research and it could be bug in PHP, bug in PHP Development Server that keeps the connections alive. But I'm not sure, no more clues.
